accounts/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

urlpatterns = [    
	path('superadmin/', login_required(AccountView.as_view()), name='superadmin'),
	path('superadmin/schemes', login_required(AccountSchemesView.as_view()), name='superadmin_schemes'),
	path('superadmin/schemes-excel', login_required(AccountSchemesExcelView.as_view()), name='superadmin_schemes_excel'),
	path('superadmin/categories', login_required(AccountCategoriesView.as_view()), name='superadmin_categories'),
	path('superadmin/categories-excel', login_required(AccountCategoriesExcelView.as_view()), name='superadmin_categories_excel'),
	path('superadmin/nominations', login_required(AccountNominationsView.as_view()), name='superadmin_nominations'),
	path('superadmin/nominations-excel', login_required(AccountNominationsExcelView.as_view()), name='superadmin_nominations_excel'),
	path('superadmin/votes', login_required(AccountVotesView.as_view()), name='superadmin_votes'),
	path('superadmin/votes-excel', login_required(AccountVotesExcelView.as_view()), name='superadmin_votes_excel'),
	path('superadmin/payments', login_required(AccountPaymentsView.as_view()), name='superadmin_payments'),
	path('superadmin/payments-excel', login_required(AccountPaymentsExcelView.as_view()), name='superadmin_payments_excel'),
	path('superadmin/messaging', login_required(AccountMessagingView.as_view()), name='superadmin_messaging'),
	path('superadmin/blog/', login_required(BlogView.as_view()), name='superadmin_blog'),   
    path('superadmin/blog-detail', login_required(BlogDetailView.as_view()), name='superadmin_blog_detail'), 
	path('superadmin/messaging/sms', login_required(AccountMessagingSMSView.as_view()), name='superadmin_messaging_sms'),
	path('superadmin/messaging/emails', login_required(AccountMessagingEmailsView.as_view()), name='superadmin_messaging_emails'),
	path('superadmin/messaging/settings', login_required(AccountMessagingSettingsView.as_view()), name='superadmin_messaging_settings'),
	path('superadmin/profile', login_required(AccountProfileView.as_view()), name='superadmin_profile'),
	
	# path('register/', RegisterView.as_view(), name='register'),
	# path('register_confirm/', RegisterConfirmView.as_view(), name='registerconfirm'),	
	path('adminlogin/', LoginView.as_view(), name='adminlogin'),
	# path('resetpassword/', ResetPasswordView.as_view(), name='resetpassword'),
	# path('resetpassword_confirm/', ResetPasswordConfirmView.as_view(), name='resetpasswordconfirm'),	
	# path('resetpassword_thanks/', TemplateView.as_view(template_name='resetpassword_thanks.html')),
    path('adminlogout/', LogoutView.as_view(), name='adminlogout'),
]

hag/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('adminpanel/', admin.site.urls),
    path('', include(('index.urls'))),
    path('', include(('nominations.urls'))),
    path('', include(('events.urls'))),
    path('', include(('awards.urls'))),
    path('', include(('accounts.urls'))),
    path('', include(('votes.urls'))),
    path('', include(('blog.urls'))),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

accounts/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils import timezone
from django.conf import settings
from .utils import *
import os
from uuid import uuid4

# Create your models here.
def path_and_rename(instance, filename):
    upload_to = 'media'
    ext = filename.split('.')[-1]
    # get filename
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext)
    else:
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
    # return the whole path to the file
    return os.path.join(upload_to, filename)

# Create your models here.
class Register(models.Model):
    fullname = models.CharField(max_length=255, blank=True, null=True, default='')
    emailaddress = models.EmailField(max_length=255, blank=True, null=True, default='')
    code = models.CharField(max_length=100, blank=True, null=True, default='')
    confirmed = models.BooleanField(blank=False,  default=False)
    expired_date = models.BigIntegerField(blank=True, null=True, default=0)
    datecreated = models.DateTimeField(default=timezone.now)
    
    def __str__(self):  
        return str(self.fullname)

class Accounts(models.Model):
    GENDER_CHOICES = (('Male','Male'), ('Female','Female'))
    user = models.ForeignKey(User, related_name="account_user", null=True, blank=True, on_delete=models.SET_NULL)
    slug = models.SlugField(unique=True, null=True, blank=True, max_length=100)
    photograph = models.ImageField(upload_to=path_and_rename, blank=True, null=True )
    fullname = models.CharField(max_length=100, blank=True, null=True )
    gender = models.CharField(max_length=50, null=True, blank=True, choices = GENDER_CHOICES, default = None) 
    phonenumber = models.CharField(max_length=100, blank=True, null=True )
    email = models.EmailField(blank=True, null=True )
    position = models.CharField(max_length=100, blank=True, null=True )
    budget = models.CharField(max_length=100, blank=True, null=True )
    code = models.CharField(max_length=100, blank=True, null=True )
    confirmed = models.BooleanField(blank=True, default=False)
    pastfirsttime = models.BooleanField(blank=True, default=False)
    admin = models.BooleanField(blank=True, default=False)
    active = models.BooleanField(blank=True, default=False)
    datecreated = models.DateTimeField(default=timezone.now)
    
    def save(self, *args, **kwargs):
        try:
            if not self.is_update_view:
                self.slug = generate_slug(self, self.fullname)
        except:
            self.slug = generate_slug(self, self.fullname)
        
        super(Accounts, self).save(*args, **kwargs)
    
    def __str__(self):
        return str(self.slug)


class UserActivity(models.Model):
	"""This is them main log module used to store logs of a user's activity"""		
	user = models.ForeignKey(Accounts, related_name='activity_user', blank=True, null=True, on_delete=models.SET_NULL)
	activity = models.TextField(null=True, blank=True)
	datecreated = models.DateTimeField(default=timezone.now)

	def __str__(self):  
		# return self.user__memberid
		return self.activity

class Telephony(models.Model):	
    """This is where country codes and related things are stored, also this is used to format phonenumbers"""
    countrycode = models.CharField(max_length=100, null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    nowithcountrycode = models.IntegerField(null=True, blank=True)
    nowithoutcountrycode = models.IntegerField(null=True, blank=True)
    supportednetworks = models.CharField(max_length=200, null=True, blank=True)
    nonetstartwith = models.IntegerField(null=True, blank=True)
    datecreated = models.DateTimeField(default=timezone.now)

    def __str__(self):  
        # return self.user__memberid
        return str(self.countrycode)


class Countries(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True, default='') 
    nicename = models.CharField(max_length=100, null=True, blank=True, default='') 
    iso = models.CharField(max_length=100, null=True, blank=True, default='') 
    iso3 = models.CharField(max_length=100, null=True, blank=True, default='') 
    numcode = models.CharField(max_length=100, null=True, blank=True, default='') 
    phonecode = models.CharField(max_length=100, null=True, blank=True, default='') 
    minimum_nsn = models.IntegerField(null=True, blank=True, default=7) 
    maximum_nsn = models.IntegerField(null=True, blank=True, default=9)
	
    def __str__(self):  
        return str(self.name)

accounts/forms.py
from django import forms
from django.forms import ModelForm
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from index.models import *
from .models import *


class RegisterForm(forms.Form):
    fullname = forms.CharField(label='Fullname')
    emailaddress = forms.CharField(label='Email')
    
    def clean_fullname(self):
        fullname = self.cleaned_data['fullname']
        return fullname        
    
    def clean_emailaddress(self):
        emailaddress = self.cleaned_data['emailaddress']		
        if not re.search((r'[\w\+@/. ]+'), emailaddress):
            raise forms.ValidationError('Email is not in the correct format, check your @ symbol and your . symbol')
        reg = Register.objects.filter(emailaddress=emailaddress).last()
        if reg:
            raise forms.ValidationError('This Email Address has already been used to register.')
        else:
            return emailaddress
        return emailaddress
    

class RegisterConfirmForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput() )
    confirmpassword = forms.CharField(label='Confirm Password', widget=forms.PasswordInput() )

    def clean_username(self):
        username = self.cleaned_data['username']		
        if not re.search(r'^\w+', username):
            raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
        
        user = User.objects.filter(username=username).last()
        if user:
            raise forms.ValidationError('Username is already taken.')
        else:
            return username

    def clean_confirmpassword(self):
        if 'password' in self.cleaned_data:		
            password = self.cleaned_data['password']
            confirmpassword = self.cleaned_data['confirmpassword']
            if password == confirmpassword:
                return confirmpassword
            raise forms.ValidationError('Passwords do not match.')

class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput() )
    
    def clean_username(self):
        username = self.cleaned_data['username']		
        try:
            User.objects.filter(username=username).last()
        except ObjectDoesNotExist:
            raise forms.ValidationError('Account does not exist.')
        return username

class ResetPasswordForm(forms.Form):
    email = forms.EmailField(label='Email')	
    def clean_email(self):
        email = self.cleaned_data['email']		
        if not re.search((r'[\w\+@/. ]+'), email):
            raise forms.ValidationError('Email is not in the correct format, check your @ symbol and your . symbol')
        try:
            User.objects.filter(email=email).last()
        except ObjectDoesNotExist:
            raise forms.ValidationError('Email is not registered with us yet.')
        return email

class ResetPasswordConfirmForm(forms.Form):
    newpassword = forms.CharField(label='Password', widget=forms.PasswordInput() )
    confirmpassword = forms.CharField(label='Confirm Password', widget=forms.PasswordInput() )

    def clean_confirmpassword(self):
        if 'newpassword' in self.cleaned_data:		
            password = self.cleaned_data['newpassword']
            confirmpassword = self.cleaned_data['confirmpassword']
            if password == confirmpassword:
                return confirmpassword
            raise forms.ValidationError('Passwords do not match.')

class ProfileForm(ModelForm):
	class Meta:
		model = Accounts
		fields = ['photograph', 'fullname', 'phonenumber', 'gender']


accounts/templates/activateaccount.html
{% extends "index_base.html" %}
{% load i18n %}
{% load static%}
{% block title %}Activation{% endblock %}
{% block description %}Activation your Accout.{% endblock %}
{% block keywords %} {% endblock %}

{% block content %}
<div class="pageheader row">
    <div class="container">
        <h2 style="padding:10px;"> ACTIVATE ACCOUNT </h2>
    </div>
</div>

<div class="row" style="background: #f5f9fd;">
<div class="container" style="max-width: 320px; padding:10px 0; margin-bottom:40px;">
    <div class="row">
        <div id="loginbox" style="margin-top:20px;" class="mainbox col-md-12  col-sm-12 ">                    
            <div class="card " style="background:#fff; border: 1px solid #ccc; border-radius:0px; box-shadow: 0 0 10px #e7e7e7; text-align:center;">
                    
                    <div style="padding:0px; border-radius:0px;" class="card-body">
                    
                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                            
              
                        <form id="activateform" class="simple-inline" role="form" method="post" action="{% url 'activateaccount' phonenumber %}">
                            {% csrf_token %}
                                <br>                                       
                                <div class="form-group col-12">
                                    <h5>Kindly Enter the CODE that was sent to you via SMS</h5>
                                </div>
                                
                                <input id="id_phonenumber" type="hidden" value="{{phonenumber}}" class="form-control" name="phonenumber"  >

                                {% if form.phonenumber.errors %}
                                  <div class="form-group col-12">
                                    <div style="padding: 3px; " id="login-alert" class="alert alert-danger col-sm-12">
                                    <p>{{form.phonenumber.errors}}</p>
                                    </div>
                                    </div>
                                    {% endif %}

                                 
                                  {% if form.activationcode.errors %}
                                  <div class="form-group col-12">
                                    <div style="padding: 3px; " id="login-alert" class="alert alert-danger col-sm-12">
                                    <p>{{form.activationcode.errors}}</p>
                                    </div>
                                    </div>
                                    {% endif %}
    
                                
                                <div class="form-group col-sm-12" >
                                <div  class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id=""><i class="fa fa-mobile"></i></span>
                                    </div>
                                    <input id="id_activationcode" type="text" value="{{ form.activationcode.value|default_if_none:''}}" class="form-control" name="activationcode" placeholder="Activation CODE" autocomplete="off" required >
                                </div>
                                </div>
                                   
                                <div class="form-group col-sm-12">
                                    <div  class="form-group">
                                        <!-- Button -->
                                        <button type="submit" id="btn-login" class="btn btn-info btn-block">Activate Account </button>
                                          
                                    </div>
                                </div>

                                <div class="form-group col-sm-12">   
                                    <div style="border-top: 1px solid #eee; padding-top:2px; font-size:85%; text-align:center;"><a >Resend Code</a></div>
                                    <div style="border-top: 1px solid #eee; padding-top:2px; font-size:85%; text-align:center;"><a href="{% url 'register' %}">Back to Registration</a></div>                         
                                                             
                                                                  
                                </div> 

    
    
                            </form> 

   
                        
                        </div>                     

            </div> 

</div>
</div>

</div>

</div>










 
 {% endblock %}

accounts/templates/register.html
{% extends "index_base.html" %}
{% load i18n %}
{% load static%}
{% block title %}Register{% endblock %}
{% block description %}Register for New Account{% endblock %}
{% block keywords %}  {% endblock %}

{% block content %}
<div class="pageheader row">
    <div class="container">
        <h2 style="padding:10px;"> REGISTER </h2>
    </div>
</div>

<div class="row" style="background: #f5f9fd;">
<div class="container" style="max-width: 350px; padding:10px 0; margin-bottom:40px;">
    <div class="row">
        <div id="loginbox" style="margin-top:20px;" class="mainbox col-md-12  col-sm-12 ">                    
            <div class="carddiv" style="background:#fff; ">                    
                    <div style="padding:0px; border-radius:0px;" class="card-body">
                    
                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                                          
                        <form id="form" class="simple-inline" role="form" method="post" action="{% url 'register' %}">
                            {% csrf_token %}
                            <input type="hidden" id="g-recaptcha-response" name="g-recaptcha-response" value="" />
                                
                                {% if messages %}
                                {% for message in messages %}
                                <!-- <div class="row"> -->
                                    <div class="col-12">
                                        {% if message.tags == 'success' %}
                                            <div class="alert alert-success" style="margin-bottom:5px;">
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
                                                {{ message }}
                                            </div>
                                        {% elif message.tags == 'info' %}
                                            <div class="alert alert-info" style="margin-bottom:5px;">
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
                                                {{ message }}
                                            </div>
                                        {% elif message.tags == 'error' %}
                                            <div class="alert alert-danger" style="margin-bottom:5px;">
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
                                                {{ message }}
                                            </div>
                                        {% elif message.tags == 'warning' %}
                                            <div class="alert alert-warning" style="margin-bottom:5px;">
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
                                                {{ message }}
                                            </div>
                                        {% endif %}
                                    </div>
                                    <p></p>
                                <!-- </div> -->
                                {% endfor %}
                                {% endif %}

                                
                                <div class="form-group col-12">
                                <div  class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id=""><i class="fa fa-user"></i></span>
                                    </div>
                                    <input id="id_fullname" type="text" class="form-control" name="fullname" value="{{ form.fullname.value|default_if_none:''}}" placeholder="FullName" required >                                      
                                </div>
                                </div>                                
                                
                                <div class="form-group col-12">
                                <div  class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id=""><i class="fa fa-envelope"></i></span>
                                    </div>
                                    <input id="id_emailaddress" type="text" class="form-control" name="emailaddress" value="{{ form.emailaddress.value|default_if_none:''}}" placeholder="Email Address" required >                                      
                                </div>
                                </div>
                                 
                                <div class="form-group col-sm-12">
                                    <div  class="form-group">
                                        <button type="submit" id="btn-login" class="btn btn-success btn-block">Register Account  </button>
                                    </div>
                                </div>
    
    
                            <div class="form-group col-sm-12">   
                                <div style="border-top: 1px solid #eee; padding-top:2px; font-size:85%; text-align:center;"><a href="{% url 'login' %}">Already have an Account? Login</a></div>                         
                                
                            </div> 
    
    
    
                            </form> 

   
                        
                        </div>                     

            </div> 

</div>
</div>

</div>

</div>










 
 {% endblock %}

accounts/templates/register_thanks.html
{% extends "index_base.html" %}
{% load i18n %}
{% load static%}
{% block title %}Register{% endblock %}
{% block description %}Register for New Account{% endblock %}
{% block keywords %} {% endblock %}

{% block content %}
<div class="pageheader row">
    <div class="container">
        <h2 style="padding:10px;"> THANK YOU </h2>
    </div>
</div>

<div style="padding: 5%; background: #f5f9fd; text-align: center;">
<img src="/static/images/email.png" alt="message" style="border-radius: 100%; padding: 20px;">
<h3>Thank you for registering </h3>
<p>We have sent you a confirmation email, please check your email to complete the process.</p>

</div>



{% endblock %}

accounts/templates/resetpassword.html
{% extends "index_base.html" %}
{% load i18n %}
{% load static%}
{% block title %}Reset Password{% endblock %}
{% block description %}Reset Account Password{% endblock %}
{% block keywords %} {% endblock %}


{% block content %}
<div class="pageheader row">
    <div class="container">
        <h2 style="padding:10px;"> RESET PASSWORD </h2>
    </div>
</div>

<div class="row" style="background: #f5f9fd;">
<div class="container" style="max-width: 400px; padding:10px 0; margin-bottom:40px;">
    <div class="row">
        <div id="loginbox" style="margin-top:20px;" class="mainbox col-md-12  col-sm-12 ">                    
            <div class="carddiv" style="background:#fff; ">
                    
                    <div style="padding:0px; border-radius:0px;" class="card-body">
                    
                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                         
                        <form id="form" class="simple-inline" role="form" method="post" action="{% url 'resetpassword' %}">
                            {% csrf_token %}
                            <input type="hidden" id="g-recaptcha-response" name="g-recaptcha-response" value="" />
                            <div class="col-12">
                                <br>
                            </div>
                            {% if messages %}
                            {% for message in messages %}
                            <!-- <div class="row"> -->
                                <div class="col-12">
                                    {% if message.tags == 'success' %}
                                        <div class="alert alert-success" style="margin-bottom:5px;">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
                                            {{ message }}
                                        </div>
                                    {% elif message.tags == 'info' %}
                                        <div class="alert alert-info" style="margin-bottom:5px;">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
                                            {{ message }}
                                        </div>
                                    {% elif message.tags == 'error' %}
                                        <div class="alert alert-danger" style="margin-bottom:5px;">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
                                            {{ message }}
                                        </div>
                                    {% elif message.tags == 'warning' %}
                                        <div class="alert alert-warning" style="margin-bottom:5px;">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
                                            {{ message }}
                                        </div>
                                    {% endif %}
                                </div>
                                
                            <!-- </div> -->
                            {% endfor %}
                            {% endif %}

                            <div class="form-group col-12"> 
                                <label>Email Address:</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                                    </div>
                                    <input id="id_email" type="email" class="form-control" name="email" value="" placeholder="Email Address" required >  
                                
                                </div>
                                 
                            </div>       
                                
                            <div class="form-group col-sm-12">
                                <div  class="form-group">
                                    <!-- Button -->
                                    <button type="submit" id="btn-login" class="btn btn-info btn-block">Reset Password  </button>
                                        
                                </div>
                            </div>
    
    
                            <div class="form-group col-sm-12">   
                                <div style="border-top: 1px solid #eee; padding-top:2px; font-size:85%; text-align:center;"><a href="{% url 'login' %}">Remembered Password? Login</a></div>                         
                                                            
                            </div> 
    
    
    
                            </form> 

   
                        
                        </div>                     

            </div> 

</div>
</div>

</div>

</div>










 
 {% endblock %}

accounts/templates/resetpassword_thanks.1.html
{% extends "index_base.html" %}
{% load i18n %}
{% load static%}
{% block title %}Password Reset{% endblock %}

{% block menu %}
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="/features/">Features</a></li>
    <li><a href="/pricing/">Pricing</a></li>
    <li><a href="/aboutus/">About Us</a></li>
    <li><a href="https://churchaffairs.wordpress.com/" target="new">Blog</a></li>
    {% if user.is_authenticated and churchname %} 

    <li><a href="/churchprofile/">Church Profile</a></li> 
      <li><a href="/logout/">Logout</a></li>                               
    {% else %}
        <li><a href="/registerbranch/">Register</a></li>
        <li><a href="/login/">Login</a></li>
    {% endif %}
{% endblock %}


{% block content %}

<div class="pageheader row">

</div>

<div style="padding: 5%;" align="center">
<img src="/static/images/email.png" alt="message" style="border-radius: 100%; padding: 20px;">
<h3>You are almost Done!!!</h3>
<p>We have just sent you a password reset link</p>
<p>Please <b>check your inbox</b> to find the e-mail and <b>complete your password reset.</b>.</p>
<p>Please <b>check your spam folder</b> if you cannot find it in your inbox. </p>
		

</div>



{% endblock %}

accounts/templates/resetpassword_thanks.html
{% extends "index_base.html" %}
{% load i18n %}
{% load static%}
{% block title %}Thank You{% endblock %}
{% block description %}Thank You{% endblock %}
{% block keywords %} {% endblock %}


{% block content %}
<div class="pageheader row">
    <div class="container">
        <h2 style="padding:10px;"> PASSWORD RESET </h2>
    </div>
</div>

<div style="padding: 5%; background:#f5f9fd;">
    <img src="/static/images/email.png" alt="message" style="border-radius: 100%; padding: 20px;">
    <h3>You are almost Done!!!</h3>
    <p>We have just sent you a password reset link</p>
    <p>Please <b>check your inbox</b> to find the e-mail and <b>complete your password reset.</b>.</p>
    <p>Please <b>check your spam folder</b> if you cannot find it in your inbox. </p>
            
    
    </div>










 
 {% endblock %}